name: Publish Docker image

on:
  push:
    branches: [master]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2